### ISSUE TITLE
Feature: Add whatlang language identifier.

### ISSUE THREAD

**Issue by TomBurdge** [abstractqqq/polars_istr#14]
I have been having some fun with polars plugins and written (with tests) integration with the [what-lang crate](https://docs.rs/whatlang/latest/whatlang/index.html).

The scope is three functions:
* **what_lang** - can identify a string's language to either: English name for the language, language name, or language code.
* **what_lang_confidence** -floating point confidence score for identification.
* **what_lang_reliable** - boolean for reliable/not. (I haven't looked into great detail for the relationship between this and what_lang_confidence. Both methods are straight out of the crate).

I know this is a little different from the more standard format string processing you have so far. Would you be open to a PR?

I am keen to learn more and better rust, so would be more than happy to respond to any changes you request to the contribution.

**Comment by abstractqqq** [comment]
Imo this is probably better done outside a dataframe. The user can turn a string column into a list of strings and pass to a Python Wrapper of what lang. 

Someone needs to develop a Python wrapper for that though. 

@ctdunc ideas?

**Comment by ctdunc** [comment]
I think this makes sense as a Polars plugin. Taking e.g. chat data and grouping by `user > language` is a pretty reasonable use case that can't easily be done by passing to a python list. 
This would also make a good standalone package.

I think it is probably beyond the scope of "identifier strings/standardized formats" but would be happy to help stand this up as its own plugin, or expand the scope of polars_istr. @abstractqqq 

Neat idea! I wonder what language would be guessed for US037833100

**Comment by TomBurdge** [comment]
Thanks for your thoughts both! :)
I am now thinking of extending this to a few other crates: lingua-rs, rust-cld2, and whichlang.
So, I think it will make sense as a stand-alone library.
